[BUGFIX] Fix recording of last visited node for sub requests
The aspect introduced in I964f0d1dc05b14e8bc6e0b866583513b91e08769
assumes that the current request is the main ActionRequest, which
is not the case if a widget is rendered. In that situation Neos would
fail with this error message:

Fatal error: Call to undefined method TYPO3\Flow\Mvc\ActionRequest::getUri()
in TYPO3_Neos_Aspect_LastVisitedNodeAspect.php on line 55

Since aspects are more expensive and the introduced aspect only
advised a single method in a single controller, I moved the behavior
to the end of the showAction() and removed the aspect again.

Change-Id: Ie00a40781f0b5375e4b3ee1a8d4c7c1e548bf5fa
Related: #45361